### ISSUE TITLE
Heroku push succeded with a failed migration

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#144]
See `https://github.com/pooh-labs/eaterslab/pull/143/checks?check_run_id=704199937` for run log. Step "Deploy to Heroku" contains error traceback.

**Comment by kantoniak** [comment]
It may be a problem with Heroku pushes with multiple branches. I ran PostgreSQL setup locally and everything seems to work fine.

**Comment by avan1235** [comment]
@kantoniak I think that the problem is that I was working also on the server part of the system and I'va change on dev version the column of model from 'camera_id' to 'camera' (as I have found out that it should not be treated as the foreign key but rather like refrence to foreign object so namin with 'id' in name is not proper - it is also visible in your code where you use the camera_id_id naming which is confising). I think you can try to do also in your branch the change from camera_id to camera to fix described probelem (or just ignore this failing run asa on the master branch it should work fine as the model wasn't changed)

**Comment by kantoniak** [comment]
OK, closing now.
